### ISSUE TITLE
MIT license file?

### ISSUE THREAD

**Issue by esksak** [wilsonjackson/add-stream#1]
Hi, we would like to credit the module to our app's acknowledgement, 
however there seems no LICENSE file nor description on README. 
According to the package.json and README, this module is under MIT license. 
Could you point me out where the license is?
As far as I understand, We need to know at least the copyright.
Thanks in advance.

**Comment by wilsonjackson** [comment]
I added the MIT license text to the README. Do you need me to push the updated readme to npm for you to be able to use it?

**Comment by esksak** [comment]
Thanks!!
No, it won't be necessary :)
I will git clone and copy it from the README file.
